this.habilidades = {
		'Talentos': {
			'Alerta': 0,
			'Atletismo': 0,
			'Callejeo': 0,
			'Empatia': 0,
			'Esquivar': 0,
			'Expresion': 0,
			'Intimidacion': 0,
			'Liderazgo': 0,
			'Pelea': 0,
			'Subterfugio': 0,
		},
		'Tecnicas': {
			'ArmasCC': 0,
			'ArmasDeFuego': 0,
			'Conducir': 0,
			'Etiqueta': 0,
			'Interpretacion': 0,
			'Pericias': 0,
			'Seguridad': 0,
			'Sigilo': 0,
			'Superviciencia': 0,
			'TratoConAnimales': 0,
		},
		'Conocimientos': {
			'Academicismo': 0,
			'Cinecias': 0,
			'Finanzas': 0,
			'Informatica': 0,
			'Investigacion': 0,
			'Leyes': 0,
			'Linguistica': 0,
			'Medicina': 0,
			'Ocultismo': 0,
			'Politica': 0,
		},
	};